import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Providers from "@/components/providers";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: Readonly<{
  children: React.ReactNode,
  session:any
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers session={session}>
        <Navbar />
        {children}
        <Footer />
      </Providers>
      </body>
    </html>
  );
}
